workflows:
  version: 2
  multi-test:
    jobs:
      - test-node6
      - test-node8
      - test-node10
  test_and_publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
  static_analysis:
    jobs:
      - test
      - size:
          requires:
            - test
      - coverage:
          requires:
            - test
      - snyk:
          context: snyk
          requires:
            - test

version: 2
jobs:
  node-base-test: &node-base-test
    working_directory: ~/analytics-node
    docker:
      - image: node
    steps:
      - checkout
      - restore_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test --tap | yarn run tap-xunit >> test-results.xml
      - store_test_results:
          path: test-results.xml
      - store_artifacts:
          path: test-results.xml
      - persist_to_workspace:
          root: .
          paths: [.]

  test-node6:
    <<: *node-base-test
    docker:
      - image: circleci/node:6-browsers
  test-node8:
    <<: *node-base-test
    docker:
      - image: circleci/node:8-browsers
  test-node10:
    <<: *node-base-test
    docker:
      - image: circleci/node:10-browsers
  test:
    <<: *node-base-test
    docker:
      - image: circleci/node:10-browsers
  coverage:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: yarn run report-coverage
  size:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: yarn run size
  snyk:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: yarn run snyk test --severity-threshold=high
      - run: yarn run snyk monitor
  publish:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm publish .
